"""
Rename semantic type to semantic category.

Revision ID: 843f6d216d10
Revises: 3d6aaebdc526
Create Date: 2025-11-11 10:54:06.010773

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy.vector import VECTOR
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "843f6d216d10"
down_revision: str | Sequence[str] | None = "3d6aaebdc526"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "feature",
        "semantic_type_id",
        new_column_name="semantic_category_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        nullable=False,
    )

    op.alter_column(
        "feature",
        "set_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "feature",
        "tag_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'Miscellaneous'::text"),
    )
    op.alter_column(
        "feature",
        "feature",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "feature",
        "value",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "feature",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "feature",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column("feature", "embedding", existing_type=VECTOR(), nullable=True)
    op.drop_index(op.f("idx_feature_set_id_semantic_type"), table_name="feature")
    op.drop_index(op.f("idx_feature_set_semantic_type_tag"), table_name="feature")
    op.drop_index(
        op.f("idx_feature_set_semantic_type_tag_feature"),
        table_name="feature",
    )
    op.create_index(
        "idx_feature_set_id_semantic_category",
        "feature",
        ["set_id", "semantic_category_id"],
        unique=False,
    )
    op.create_index(
        "idx_feature_set_semantic_category_tag",
        "feature",
        ["set_id", "semantic_category_id", "tag_id"],
        unique=False,
    )
    op.create_index(
        "idx_feature_set_semantic_category_tag_feature",
        "feature",
        ["set_id", "semantic_category_id", "tag_id", "feature"],
        unique=False,
    )
    op.alter_column(
        "history",
        "content",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "history",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "history",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "set_ingested_history",
        "ingested",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "set_ingested_history",
        "ingested",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "history",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "history",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "history",
        "content",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.add_column(
        "feature",
        sa.Column(
            "semantic_type_id",
            sa.VARCHAR(),
            server_default=sa.text("'default'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index("idx_feature_set_semantic_category_tag_feature", table_name="feature")
    op.drop_index("idx_feature_set_semantic_category_tag", table_name="feature")
    op.drop_index("idx_feature_set_id_semantic_category", table_name="feature")
    op.create_index(
        op.f("idx_feature_set_semantic_type_tag_feature"),
        "feature",
        ["set_id", "semantic_type_id", "tag_id", "feature"],
        unique=False,
    )
    op.create_index(
        op.f("idx_feature_set_semantic_type_tag"),
        "feature",
        ["set_id", "semantic_type_id", "tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_feature_set_id_semantic_type"),
        "feature",
        ["set_id", "semantic_type_id"],
        unique=False,
    )
    op.alter_column(
        "feature",
        "embedding",
        existing_type=VECTOR(),
        nullable=False,
    )
    op.alter_column(
        "feature",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "feature",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "feature",
        "value",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "feature",
        "feature",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "feature",
        "tag_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'Miscellaneous'::text"),
    )
    op.alter_column(
        "feature",
        "set_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("feature", "semantic_category_id")
    # ### end Alembic commands ###
